---
- name: Remove specified Ollama models
  ansible.builtin.command:
    cmd: "{{ ollama_check_file_path }} rm {{ item.name }}"
  loop: "{{ ollama_models | selectattr('state', 'equalto', 'absent') | list }}"
  register: ollama_rm_result
  failed_when:
    - ollama_rm_result.rc != 0
    - "'not found' not in ollama_rm_result.stderr"
  changed_when: ollama_rm_result.rc == 0

- name: List installed Ollama models
  ansible.builtin.command:
    cmd: "{{ ollama_check_file_path }} list"
  register: ollama_list_result
  changed_when: false
  when: ollama_models | selectattr('state', 'equalto', 'present') | list | length > 0

- name: Pull specified Ollama models
  ansible.builtin.command:
    cmd: "{{ ollama_check_file_path }} pull {{ ('--insecure ' if (item.insecure | default(false)) else '') + item.name }}"
  loop: "{{ ollama_models | selectattr('state', 'equalto', 'present') | list }}"
  changed_when: true
  when: >-
    ollama_list_result is skipped or
    not (ollama_list_result.stdout_lines | select('match', '^' + item.name + '(:|\\s|$)') | list | length > 0)
